language: objective-c
osx_image: xcode8.3
xcode_workspace: PhotoWall2.xcworkspace
xcode_scheme: PhotoWall2

script:
  - xcodebuild -scheme PhotoWall2 -workspace Photowall2.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
